version: "3"

services:
  backend:
    build: ./backend
    container_name: doctor-backend
    restart: always
    environment:
      MONGO_URI: "mongodb+srv://salilgupta332:12345@cluster0.bo9gx3v.mongodb.net/"
      PORT: 4000
      ADMIN_EMAIL: admin@demo.com
      ADMIN_PASSWORD: 12345678
      JWT_SECRET: mysecret123
      CLOUDINARY_CLOUD_NAME: debvcsca2
      CLOUDINARY_API_KEY: 618157536949339
      CLOUDINARY_API_SECRET: Ohe5OBErVzbfj-_5gRs0g5qZ7JI
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://localhost:4000
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
    container_name: doctor-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

  admin:
    build:
      context: ./admin
      args:
        - VITE_BACKEND_URL=http://localhost:4000
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
    container_name: doctor-admin
    restart: always
    depends_on:
      - backend
    ports:
      - "5174:5174"

