version: "3"

services:
  backend:
    build: ./backend
    container_name: doctor-backend
    restart: always
    environment:
      MONGO_URL: "mongodb+srv://salilgupta332:12345@cluster0.bo9gx3v.mongodb.net/"
      PORT: 4000
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: doctor-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

  admin:
    build: ./admin
    container_name: doctor-admin
    restart: always
    depends_on:
      - backend
    ports:
      - "5174:5174"
